# Generated by Django 5.0.3 on 2025-07-22 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="tittle",
            new_name="title",
        ),
    ]
