# Generated by Django 5.0.3 on 2025-07-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0002_rename_tittle_department_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="create_time",
            field=models.DateField(verbose_name="入职时间"),
        ),
    ]
