# Generated by Django 5.0.3 on 2025-07-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0004_prettynum"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=32, verbose_name="用户名")),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
            ],
        ),
        migrations.AlterField(
            model_name="prettynum",
            name="level",
            field=models.SmallIntegerField(
                choices=[(1, "一级"), (3, "三级"), (2, "二级"), (4, "四级")],
                default=1,
                verbose_name="级别",
            ),
        ),
    ]
