# Generated by Django 5.0.3 on 2025-09-15 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0005_admin_alter_prettynum_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prettynum",
            name="level",
            field=models.SmallIntegerField(
                choices=[(1, "一级"), (4, "四级"), (3, "三级"), (2, "二级")],
                default=1,
                verbose_name="级别",
            ),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.SmallIntegerField(
                        choices=[(1, "紧急"), (2, "重要"), (3, "临时")],
                        default=1,
                        verbose_name="级别",
                    ),
                ),
                ("title", models.CharField(max_length=64, verbose_name="标题")),
                ("detail", models.TextField(verbose_name="详细信息")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.admin",
                        verbose_name="负责人",
                    ),
                ),
            ],
        ),
    ]
