# Generated by Django 5.0.3 on 2025-09-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0007_alter_prettynum_level_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Boss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="姓名")),
                ("age", models.IntegerField(verbose_name="年龄")),
                ("img", models.CharField(max_length=128, verbose_name="头像")),
            ],
        ),
        migrations.AlterField(
            model_name="prettynum",
            name="level",
            field=models.SmallIntegerField(
                choices=[(1, "一级"), (2, "二级"), (4, "四级"), (3, "三级")],
                default=1,
                verbose_name="级别",
            ),
        ),
    ]
