# Generated by Django 5.0.3 on 2025-09-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0008_boss_alter_prettynum_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="名称")),
                ("count", models.IntegerField(verbose_name="入口")),
                (
                    "img",
                    models.FileField(
                        max_length=128, upload_to="city/", verbose_name="Logo"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="prettynum",
            name="level",
            field=models.SmallIntegerField(
                choices=[(2, "二级"), (4, "四级"), (1, "一级"), (3, "三级")],
                default=1,
                verbose_name="级别",
            ),
        ),
        migrations.AlterField(
            model_name="prettynum",
            name="status",
            field=models.SmallIntegerField(
                choices=[(2, "未占用"), (1, "已占有")], default=2, verbose_name="状态"
            ),
        ),
    ]
